# Generated by Django 4.2.9 on 2024-04-07 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("mysocial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="author_url",
            field=models.URLField(
                default=django.utils.timezone.now, max_length=1000, unique=True
            ),
            preserve_default=False,
        ),
    ]
