# Generated by Django 4.2.9 on 2024-04-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_url',
            field=models.URLField(max_length=1000, null=True, unique=True),
        ),
    ]
