# Generated by Django 4.2.9 on 2024-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0002_author_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
