# Generated by Django 4.2.9 on 2024-02-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0003_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
