# Generated by Django 4.2.9 on 2024-04-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysocial", "0003_alter_author_author_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profileImage",
            field=models.ImageField(
                blank=True,
                max_length=1000,
                null=True,
                upload_to="static/images/profile_images/",
            ),
        ),
    ]
