# Generated by Django 4.2.9 on 2024-02-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysocial", "0003_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
