# Generated by Django 4.2.9 on 2024-02-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0004_remoteserver_author_github_author_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_id',
            new_name='authorId',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='display_name',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='profile_image',
            new_name='profileImage',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='url_id',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='author',
            name='profile_url',
        ),
    ]
