# Generated by Django 4.2.9 on 2024-02-24 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0005_rename_author_id_author_authorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mysocial.author')),
            ],
        ),
    ]
