# Generated by Django 4.2.9 on 2024-02-25 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0006_alter_author_displayname_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url_id',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='postId',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mysocial.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
