# Generated by Django 4.2.9 on 2024-02-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0008_alter_post_author_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, null=True)),
                ('summary', models.CharField(max_length=2000, null=True)),
                ('actor', models.JSONField()),
                ('object', models.JSONField()),
            ],
        ),
    ]
