# Generated by Django 4.2.9 on 2024-02-25 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0009_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='type',
            field=models.CharField(default='Follow', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=30),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='comment', max_length=30)),
                ('comment', models.TextField(max_length=2000)),
                ('contentType', models.CharField(max_length=30)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('commentId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='mysocial.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='mysocial.post')),
            ],
        ),
    ]
