# Generated by Django 4.2.9 on 2024-02-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0012_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='attributes',
        ),
        migrations.AddField(
            model_name='follower',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='mysocial.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='mysocial.author'),
        ),
    ]
