# Generated by Django 4.2.9 on 2024-02-28 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0014_alter_author_authorid_alter_post_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authorId',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
