# Generated by Django 4.2.9 on 2024-02-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0015_alter_author_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestfollowing', to='mysocial.author'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestfollowed', to='mysocial.author'),
        ),
    ]
