# Generated by Django 4.2.9 on 2024-03-11 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0020_alter_follower_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.URLField(default='https://www.w3.org/ns/activitystreams')),
                ('summary', models.CharField(max_length=255)),
                ('type', models.CharField(default='Like', max_length=50)),
                ('object_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='mysocial.author')),
            ],
        ),
    ]
