# Generated by Django 4.2.9 on 2024-03-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0021_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(null=True),
        ),
    ]
