# Generated by Django 4.2.9 on 2024-03-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0023_alter_post_count_alter_post_likescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
