# Generated by Django 4.2.9 on 2024-03-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysocial", "0024_author_bio_alter_author_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profileImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/profile_images"
            ),
        ),
    ]
