# Generated by Django 4.2.9 on 2024-03-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0025_alter_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('POST', 'Post'), ('IMAGE', 'Image'), ('COMMONMARK', 'Commonmark')], default='post', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=30),
        ),
    ]
