# Generated by Django 4.2.9 on 2024-03-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0026_alter_post_type_alter_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/posts_images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/profile_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('POST', 'Post'), ('IMAGE', 'Image'), ('COMMONMARK', 'Commonmark')], default='post', max_length=30, null=True),
        ),
    ]
