# Generated by Django 4.2.9 on 2024-03-18 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0030_alter_inbox_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteServer',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='node_cred',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='node',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='node',
            name='host',
        ),
        migrations.RemoveField(
            model_name='node',
            name='user',
        ),
        migrations.AddField(
            model_name='node',
            name='url',
            field=models.CharField(default='127.0.0.1:8000/authors', max_length=30),
        ),
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 5, 42, 14, 559597, tzinfo=datetime.timezone.utc)),
        ),
    ]
