# Generated by Django 4.2.9 on 2024-03-18 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0031_delete_remoteserver_rename_node_cred_node_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 6, 25, 32, 180705, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.CharField(default='127.0.0.1:8000/authors', max_length=1000),
        ),
    ]
