# Generated by Django 4.2.9 on 2024-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0032_alter_inbox_timestamp_alter_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
