# Generated by Django 4.2.9 on 2024-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0033_alter_inbox_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='authors_url',
            field=models.CharField(default='127.0.0.1:8000/authors', max_length=1000),
        ),
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.CharField(default='127.0.0.1:8000/', max_length=1000),
        ),
    ]
