# Generated by Django 4.2.9 on 2024-03-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0034_node_authors_url_alter_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='authors_url',
            field=models.URLField(default='127.0.0.1:8000/authors', max_length=1000),
        ),
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.URLField(default='127.0.0.1:8000/', max_length=1000),
        ),
    ]
