# Generated by Django 4.2.9 on 2024-03-19 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0035_alter_node_authors_url_alter_node_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_inbox', models.URLField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_follow', to='mysocial.author')),
            ],
        ),
    ]
