# Generated by Django 4.2.9 on 2024-03-19 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0036_remotefollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='inbox_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
