# Generated by Django 4.2.9 on 2024-03-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0037_inbox_inbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted')], default='PUBLIC', max_length=30),
        ),
    ]
